build:tags:
  stage: build
  tags:
    - shell
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  timeout: 12h
  script:
    # Combine authentication for both GITLAB and GITHUB Registries into one config.json
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"},\"$GITHUB_REGISTRY\":{\"username\":\"$GITHUB_USER\",\"password\":\"$GITHUB_API_KEY\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    # Clean and prepare contexts
    - rm -rf $CI_PROJECT_DIR/docker/cache
    - mkdir -p /kaniko_context_gitlab /kaniko_context_github
    - cp -r $CI_PROJECT_DIR/* /kaniko_context_gitlab
    - cp -r $CI_PROJECT_DIR/* /kaniko_context_github
    # Run Kaniko with the Repository Directories as Context
    - /kaniko/executor --cache=false --context /kaniko_context_gitlab --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - /kaniko/executor --cache=false --context /kaniko_context_github --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $GITHUB_REGISTRY/$GITHUB_USER/$CI_PROJECT_NAME:$CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG'

build:latest-master:
  stage: build
  tags:
    - shell
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  timeout: 12h
  script:
    # Combine authentication for both GITLAB and GITHUB Registries into one config.json
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"},\"$GITHUB_REGISTRY\":{\"username\":\"$GITHUB_USER\",\"password\":\"$GITHUB_API_KEY\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    # Clean and prepare contexts
    - rm -rf $CI_PROJECT_DIR/docker/cache
    - mkdir -p /kaniko_context_gitlab /kaniko_context_github
    - cp -r $CI_PROJECT_DIR/* /kaniko_context_gitlab
    - cp -r $CI_PROJECT_DIR/* /kaniko_context_github
    # Run Kaniko with the Repository Directories as Context
    - /kaniko/executor --cache=false --context /kaniko_context_gitlab --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $CI_REGISTRY_IMAGE:latest
    - /kaniko/executor --cache=false --context /kaniko_context_github --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $GITHUB_REGISTRY/$GITHUB_USER/$CI_PROJECT_NAME:latest