build:tags-gitlab:
  stage: build
  tags:
    - shell
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  timeout: 12h
  script:
    # Combine authentication for GitLab registry
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    # Clean contexts for GitLab
    - rm -rf $CI_PROJECT_DIR/docker/cache
    # Run Kaniko for GitLab registry with the specific tag
    - /kaniko/executor --cache=false --context /kaniko_context_gitlab --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

build:tags-github:
  stage: build
  tags:
    - shell
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  timeout: 12h
  script:
    # Combine authentication for GitHub registry
    - echo "{\"auths\":{\"$GITHUB_REGISTRY\":{\"username\":\"$GITHUB_USER\",\"password\":\"$GITHUB_API_KEY\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    # Clean contexts for GitHub
    - rm -rf $CI_PROJECT_DIR/docker/cache
    # Run Kaniko for GitHub registry with the specific tag
    - /kaniko/executor --cache=false --context /kaniko_context_github --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $GITHUB_REGISTRY/$GITHUB_USER/$CI_PROJECT_NAME:$CI_COMMIT_TAG

build:latest-master-gitlab:
  stage: build
  tags:
    - shell
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  timeout: 12h
  script:
    # Combine authentication for GitLab registry
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    # Prepare context (GitLab)
    - rm -rf $CI_PROJECT_DIR/docker/cache
    # Run Kaniko for GitLab registry
    - /kaniko/executor --cache=false --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $CI_REGISTRY_IMAGE:latest

build:latest-master-github:
  stage: build
  tags:
    - shell
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  timeout: 12h
  script:
    # Combine authentication for GitHub registry
    - echo "{\"auths\":{\"$GITHUB_REGISTRY\":{\"username\":\"$GITHUB_USER\",\"password\":\"$GITHUB_API_KEY\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    # Prepare context (GitHub)
    - rm -rf $CI_PROJECT_DIR/docker/cache
    # Run Kaniko for GitHub registry
    - /kaniko/executor --cache=false --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $GITHUB_REGISTRY/$GITHUB_USER/$CI_PROJECT_NAME:latest
