build:tags:
  stage: build
  tags:
    - shell
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  timeout: 12h
  script:
    # Combine authentication for both GITLAB and GITHUB Registries into one config.json
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"},\"$GITHUB_REGISTRY\":{\"username\":\"$GITHUB_USER\",\"password\":\"$GITHUB_PAT\"}}}" > /kaniko/.docker/config.json
    - rm -rf $CI_PROJECT_DIR/docker/cache
    - /kaniko/executor --cache=false --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - /kaniko/executor --cache=false --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination ghcr.io/$GITHUB_USER/$CI_PROJECT_NAME:$CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG'

build:latest-master:
  stage: build
  tags:
    - shell
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  timeout: 12h
  script:
    # Combine authentication for both GITLAB and GITHUB Registries into one config.json
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"},\"$GITHUB_REGISTRY\":{\"username\":\"$GITHUB_USER\",\"password\":\"$GITHUB_PAT\"}}}" > /kaniko/.docker/config.json
    # Run Kaniko with the project directory as the context
    - rm -rf $CI_PROJECT_DIR/docker/cache
    - /kaniko/executor --cache=false --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $CI_REGISTRY_IMAGE:latest
    - /kaniko/executor --cache=false --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination ghcr.io/$GITHUB_USER/$CI_PROJECT_NAME:latest